apiVersion: apps/v1
kind: Deployment
metadata:
  name: dream-app-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dream-app-backend
  template:
    metadata:
      labels:
        app: dream-app-backend
    spec:
      containers:
        - name: dream-app-backend
          image: dillax/dream-backend:37df9597b2e7f88a25f7d86b202584f6520d1fb5
          ports:
            - containerPort: 3000
---


---

