apiVersion: apps/v1
kind: Deployment
metadata:
  name: dream-app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dream-app-frontend
  template:
    metadata:
      labels:
        app: dream-app-frontend
    spec:
      containers:
        - name: dream-app-frontend
          image: dillax/dream-frontend:1102275c0ff1571b16e6b71838b78cde4be5b410
          ports:
            - containerPort: 80
          